name: 'Tell your name'
description: 'Prints your name'
inputs:
  who-to-greet:  # id of input
    description: 'your name'
    required: true
    default: 'developer'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
