name: 'Tell your name'
description: 'Prints your name'
author: 'Mykyta Shevelov'
branding:
  icon: watch
  color: green
inputs:
  name:  # id of input
    description: 'your name'
    required: true
    default: 'developer'
runs:
  using: 'node12'
  main: 'index.js'
