name: "Prints your name"
on: [push]

jobs:
  file_presence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Prints the name"
        uses: Mykyta/hello-world-javascript-action@7
        with:
          file: "README.md"
